(function () {
  // Manually reconciled against all 34 rendered pages of AS_MENU_2025.pdf.
  // Fields: menu section, item/variant name, selling price before VAT, department, PDF page.
  const rows = [
    ['Kids', 'Breaded Chicken for Kids', 35, 'dep-kitchen', 2],
    ['Kids', 'Grilled Kofta for Kids', 35, 'dep-grill', 2],
    ['Hot Soups', 'Orzo Soup', 15, 'dep-kitchen', 3],
    ['Hot Soups', 'Lentil Soup', 18, 'dep-kitchen', 3],
    ['Hot Soups', 'Trotters Soup', 33, 'dep-kitchen', 3],
    ['Salads & Cold Appetizers', 'Oriental Salad', 15, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Pickled Eggplant & Tomato', 17, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Whisky Salad (Spicy)', 10, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Tahini', 15, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Garlic Paste', 15, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Yogurt Cucumber', 15, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Moutabal', 19, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Hummus', 19, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Tabbouleh', 28, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Fattoush', 28, 'dep-kitchen', 4],
    ['Salads & Cold Appetizers', 'Homemade Pickles', 10, 'dep-kitchen', 4],
    ['Hot Appetizers', 'Kebbeh', 25, 'dep-kitchen', 5],
    ['Hot Appetizers', 'Cheese Samboussa', 20, 'dep-kitchen', 5],
    ['Hot Appetizers', 'Meat Samboussa', 20, 'dep-kitchen', 5],
    ['Hot Appetizers', 'Alex Veal Liver', 25, 'dep-kitchen', 5],
    ['Hot Appetizers', 'Rokak', 35, 'dep-kitchen', 5],
    ['Hot Appetizers', 'Hummus with Meat', 35, 'dep-kitchen', 5],
    ['Hot Appetizers', 'Hawawshy - 1 Loaf', 25, 'dep-kitchen', 5],
    ['Hot Appetizers', 'Alex Soujok', 35, 'dep-kitchen', 5],
    ['Abu Shakra Grills', 'A.S. Mix Grill [Plate]', 80, 'dep-grill', 6],
    ['Abu Shakra Grills', 'A.S. Mix Grill [1 kg]', 200, 'dep-grill', 6],
    ['Abu Shakra Grills', 'Lamb Kofta [Plate]', 60, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Lamb Kofta [1 kg]', 175, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Lamb Kebab [Plate]', 70, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Lamb Kebab [1 kg]', 190, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Lamb Kebab & Kofta [Plate]', 65, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Lamb Kebab & Kofta [1 kg]', 185, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Kofta & Chops [Plate]', 75, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Kofta & Chops [1 kg]', 190, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Kebab & Chops [Plate]', 85, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Kebab & Chops [1 kg]', 210, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Kebab, Kofta & Chops [Plate]', 85, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Kebab, Kofta & Chops [1 kg]', 210, 'dep-grill', 7],
    ['Abu Shakra Grills', 'Kebab, Tarb & Chops [Plate]', 90, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Kebab, Tarb & Chops [1 kg]', 210, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Lamb Chops [Plate]', 95, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Lamb Chops [1 kg]', 250, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Tarb [Plate]', 80, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Tarb [1 kg]', 200, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Shish Tawouk [Plate]', 50, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Shish Tawouk [1 kg]', 150, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Mix Grill Meat [Plate]', 85, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Mix Grill Meat [1 kg]', 210, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Grilled Soujok [Plate]', 65, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Grilled Soujok [1 kg]', 170, 'dep-grill', 8],
    ['Abu Shakra Grills', 'Half Grilled Chicken', 40, 'dep-grill', 8],
    ['New Items', 'Smoked Salmon & Avocado Salad', 85, 'dep-kitchen', 9],
    ['New Items', 'Turbo Tagine', 90, 'dep-kitchen', 9],
    ['New Items', 'Grilled Lamb Ribs', 140, 'dep-grill', 9],
    ['New Items', 'Lamb Tenderloin & Grilled Pigeon', 150, 'dep-grill', 10],
    ['New Items', 'Lamb Fillet Platter', 100, 'dep-grill', 10],
    ['New Items', 'Lamb Fillet [1 kg]', 260, 'dep-grill', 10],
    ['New Items', 'Grilled Salmon', 120, 'dep-grill', 10],
    ['Main Dishes', 'Stuffed Pigeon [1 piece]', 65, 'dep-kitchen', 11],
    ['Main Dishes', 'Stuffed Pigeon [2 pieces]', 130, 'dep-kitchen', 11],
    ['Main Dishes', 'Half Roasted Duck', 95, 'dep-kitchen', 11],
    ['Main Dishes', 'Lamb Shank with Rice & Vegetables', 70, 'dep-kitchen', 11],
    ['Main Dishes', 'Lamb Shank Fattah', 70, 'dep-kitchen', 11],
    ['Main Dishes', 'Veal Fattah', 60, 'dep-kitchen', 11],
    ['Main Dishes', 'Trotters Fattah', 65, 'dep-kitchen', 11],
    ['International Dishes', 'Breaded Chicken', 65, 'dep-kitchen', 12],
    ['International Dishes', 'Veal Picatta', 90, 'dep-kitchen', 12],
    ['International Dishes', 'Veal Escalope', 80, 'dep-kitchen', 12],
    ['A.S. Tagines', 'Kebab Hallah with Rice', 60, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Oxtail Onion with Rice', 60, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Vine Leaves Trotter', 65, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Molokhiya with Chicken & Rice', 50, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Molokhiya with Meat & Rice', 60, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Potato with Meat & Rice', 55, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Okra with Meat & Rice', 60, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Moussaka with Minced Meat & Rice', 50, 'dep-kitchen', 13],
    ['A.S. Tagines', 'Taro with Meat & Rice', 60, 'dep-kitchen', 13],
    ['Egyptian Plain Vegetables', 'Molokhiya [Solo]', 15, 'dep-kitchen', 14],
    ['Egyptian Plain Vegetables', 'Molokhiya [with Rice]', 30, 'dep-kitchen', 14],
    ['Egyptian Plain Vegetables', 'Potato [Solo]', 15, 'dep-kitchen', 14],
    ['Egyptian Plain Vegetables', 'Potato [with Rice]', 30, 'dep-kitchen', 14],
    ['Egyptian Plain Vegetables', 'Taro [Solo]', 18, 'dep-kitchen', 14],
    ['Egyptian Plain Vegetables', 'Taro [with Rice]', 33, 'dep-kitchen', 14],
    ['Egyptian Plain Vegetables', 'Okra [Solo]', 18, 'dep-kitchen', 14],
    ['Egyptian Plain Vegetables', 'Okra [with Rice]', 33, 'dep-kitchen', 14],
    ['Dolma & Pasta', 'Bechamel Macaroni', 30, 'dep-kitchen', 15],
    ['Dolma & Pasta', 'Stuffed Vine Leaves', 32, 'dep-kitchen', 15],
    ['Dolma & Pasta', 'Stuffed Cabbage', 32, 'dep-kitchen', 15],
    ['Dolma & Pasta', 'Mix Dolma', 40, 'dep-kitchen', 15],
    ['Dolma & Pasta', 'Mombar', 35, 'dep-kitchen', 15],
    ['Dolma & Pasta', 'Mix Dolmas & Mombar', 50, 'dep-kitchen', 15],
    ['Side Dishes', 'White / Vermicelli Rice', 13, 'dep-kitchen', 16],
    ['Side Dishes', 'Khalta Rice with Nuts', 19, 'dep-kitchen', 16],
    ['Side Dishes', 'Plain Fattah', 15, 'dep-kitchen', 16],
    ['Side Dishes', 'Sauteed Vegetables', 20, 'dep-kitchen', 16],
    ['Seafood', 'Seafood Soup - White Creamy', 30, 'dep-kitchen', 18],
    ['Seafood', 'Seafood Soup - Pink Creamy', 30, 'dep-kitchen', 18],
    ['Seafood', 'Seafood Soup - Clear', 30, 'dep-kitchen', 18],
    ['Seafood', 'Grilled Tiger Shrimp', 70, 'dep-grill', 18],
    ['Seafood', 'Fried Calamari', 50, 'dep-kitchen', 18],
    ['Seafood', 'Seabream with Sayadiya Rice', 65, 'dep-kitchen', 19],
    ['Seafood', 'Seabass with Sayadiya Rice', 75, 'dep-kitchen', 19],
    ['Seafood', 'Fried Fillet of Hamour', 65, 'dep-kitchen', 20],
    ['Seafood', 'Seafood Tagine - White Sauce', 70, 'dep-kitchen', 20],
    ['Seafood', 'Seafood Tagine - Red Sauce', 70, 'dep-kitchen', 20],
    ['Seafood', 'Shrimp Tagine - White Sauce', 70, 'dep-kitchen', 20],
    ['Seafood', 'Shrimp Tagine - Red Sauce', 70, 'dep-kitchen', 20],
    ['Seafood', 'Molokhiya with Shrimp', 65, 'dep-kitchen', 20],
    ['Seafood', 'Rice with Shrimp', 30, 'dep-kitchen', 20],
    ['Seafood', 'Sayadiya Rice', 15, 'dep-kitchen', 20],
    ['Sandwicherie', 'Alex Liver [Solo]', 10, 'dep-kitchen', 21],
    ['Sandwicherie', 'Alex Liver [Combo]', 21, 'dep-kitchen', 21],
    ['Sandwicherie', 'Alex Sausage [Solo]', 17, 'dep-kitchen', 21],
    ['Sandwicherie', 'Alex Sausage [Combo]', 27, 'dep-kitchen', 21],
    ['Sandwicherie', 'Beef Burger [Solo]', 22, 'dep-kitchen', 21],
    ['Sandwicherie', 'Beef Burger [Combo]', 32, 'dep-kitchen', 21],
    ['Sandwicherie', 'Kofta Sandwich [Solo]', 20, 'dep-grill', 21],
    ['Sandwicherie', 'Kofta Sandwich [Combo]', 30, 'dep-grill', 21],
    ['Sandwicherie', 'Kebab Sandwich [Solo]', 30, 'dep-grill', 21],
    ['Sandwicherie', 'Kebab Sandwich [Combo]', 40, 'dep-grill', 21],
    ['Sandwicherie', 'Tarb Sandwich [Solo]', 30, 'dep-grill', 21],
    ['Sandwicherie', 'Tarb Sandwich [Combo]', 40, 'dep-grill', 21],
    ['Sandwicherie', 'Beef Fillet Cheese [Solo]', 27, 'dep-kitchen', 21],
    ['Sandwicherie', 'Beef Fillet Cheese [Combo]', 37, 'dep-kitchen', 21],
    ['Sandwicherie', 'Beef Fajita [Solo]', 25, 'dep-kitchen', 21],
    ['Sandwicherie', 'Beef Fajita [Combo]', 35, 'dep-kitchen', 21],
    ['Sandwicherie', 'Breaded Chicken Sandwich [Solo]', 17, 'dep-kitchen', 22],
    ['Sandwicherie', 'Breaded Chicken Sandwich [Combo]', 27, 'dep-kitchen', 22],
    ['Sandwicherie', 'Shish Tawouk Sandwich [Solo]', 17, 'dep-grill', 22],
    ['Sandwicherie', 'Shish Tawouk Sandwich [Combo]', 27, 'dep-grill', 22],
    ['Sandwicherie', 'Super Crunchy [Solo]', 19, 'dep-kitchen', 22],
    ['Sandwicherie', 'Super Crunchy [Combo]', 29, 'dep-kitchen', 22],
    ['Sandwicherie', 'Chicken Zinger [Solo]', 19, 'dep-kitchen', 22],
    ['Sandwicherie', 'Chicken Zinger [Combo]', 29, 'dep-kitchen', 22],
    ['Sandwicherie', 'Chicken Fajita [Solo]', 18, 'dep-kitchen', 22],
    ['Sandwicherie', 'Chicken Fajita [Combo]', 28, 'dep-kitchen', 22],
    ['Sandwicherie', 'Chicken Mozzarella [Solo]', 25, 'dep-kitchen', 22],
    ['Sandwicherie', 'Chicken Mozzarella [Combo]', 35, 'dep-kitchen', 22],
    ['Sandwicherie', 'Breaded Shrimp [Solo]', 25, 'dep-kitchen', 23],
    ['Sandwicherie', 'Breaded Shrimp [Combo]', 36, 'dep-kitchen', 23],
    ['Sandwicherie', 'Grilled Shrimp [Solo]', 26, 'dep-grill', 23],
    ['Sandwicherie', 'Grilled Shrimp [Combo]', 37, 'dep-grill', 23],
    ['Extras', 'French Fries Plate', 12, 'dep-kitchen', 23],
    ['Breakfast', 'Abu Shakra Breakfast', 42, 'dep-kitchen', 24],
    ['Breakfast', 'Continental Breakfast', 95, 'dep-kitchen', 24],
    ['Popular Dishes', 'Foul with Corn Oil', 15, 'dep-kitchen', 25],
    ['Popular Dishes', 'Foul - Olive Oil / Ghee / Butter / Alex', 19, 'dep-kitchen', 25],
    ['Popular Dishes', 'Foul with Linseed Oil', 21, 'dep-kitchen', 25],
    ['Popular Dishes', 'Falafel', 12, 'dep-kitchen', 25],
    ['Popular Dishes', 'Falafel Zinger', 16, 'dep-kitchen', 25],
    ['Popular Dishes', 'Mashed Potato', 15, 'dep-kitchen', 25],
    ['Popular Dishes', 'Moussaka', 17, 'dep-kitchen', 26],
    ['Popular Dishes', 'Cheese Tomato', 18, 'dep-kitchen', 26],
    ['Popular Dishes', 'Shakshouka', 22, 'dep-kitchen', 26],
    ['Popular Dishes', 'Fried Roumi Cheese', 25, 'dep-kitchen', 26],
    ['Popular Dishes', 'French Fries', 12, 'dep-kitchen', 26],
    ['Popular Dishes', 'Mix Fried Vegetables', 19, 'dep-kitchen', 26],
    ['Popular Dishes', 'Omelet Pastrami', 27, 'dep-kitchen', 27],
    ['Popular Dishes', 'Plain Omelet', 16, 'dep-kitchen', 27],
    ['Popular Dishes', 'Cheese Omelet', 20, 'dep-kitchen', 27],
    ['Popular Dishes', 'Boiled Egg', 15, 'dep-kitchen', 27],
    ['Breakfast Sandwiches', 'Foul Sandwich', 5, 'dep-kitchen', 28],
    ['Breakfast Sandwiches', 'Foul Special Sandwich - Olive Oil / Ghee / Butter / Alex', 7, 'dep-kitchen', 28],
    ['Breakfast Sandwiches', 'Foul with Linseed Oil Sandwich', 10, 'dep-kitchen', 28],
    ['Breakfast Sandwiches', 'Foul with Boiled Egg Sandwich', 8, 'dep-kitchen', 28],
    ['Breakfast Sandwiches', 'Falafel Sandwich', 5, 'dep-kitchen', 28],
    ['Breakfast Sandwiches', 'Falafel Zinger Sandwich', 7, 'dep-kitchen', 28],
    ['Breakfast Sandwiches', 'Mashed Potato Sandwich', 5, 'dep-kitchen', 29],
    ['Breakfast Sandwiches', 'Mashed Potato with Boiled Egg Sandwich', 8, 'dep-kitchen', 29],
    ['Breakfast Sandwiches', 'Moussaka Sandwich', 6, 'dep-kitchen', 29],
    ['Breakfast Sandwiches', 'Cheese Tomato Sandwich', 6, 'dep-kitchen', 29],
    ['Breakfast Sandwiches', 'French Fries Sandwich', 6, 'dep-kitchen', 29],
    ['Breakfast Sandwiches', 'Shakshouka Sandwich', 8, 'dep-kitchen', 29],
    ['Breakfast Sandwiches', 'French Fries with Roumi Cheese Sandwich', 9, 'dep-kitchen', 29],
    ['Breakfast Sandwiches', 'Fried Roumi Cheese Sandwich', 11, 'dep-kitchen', 30],
    ['Breakfast Sandwiches', 'Mix Fries with Falafel Sandwich', 7, 'dep-kitchen', 30],
    ['Breakfast Sandwiches', 'Hummus with Meat Sandwich', 15, 'dep-kitchen', 30],
    ['Breakfast Sandwiches', 'Egg Pastrami Sandwich', 12, 'dep-kitchen', 30],
    ['Breakfast Sandwiches', 'Fried Egg Sandwich', 8, 'dep-kitchen', 30],
    ['Breakfast Sandwiches', 'Boiled Egg Sandwich', 7, 'dep-kitchen', 30],
    ['Breakfast Sandwiches', 'Halawa with Keshta Sandwich', 13, 'dep-kitchen', 30],
    ['Breakfast Sandwiches', 'Jam with Keshta Sandwich', 13, 'dep-kitchen', 30],
    ['Hot Drinks', 'Black Tea', 6, 'dep-beverage', 31],
    ['Hot Drinks', 'Tea with Milk', 10, 'dep-beverage', 31],
    ['Hot Drinks', 'Green Tea', 10, 'dep-beverage', 31],
    ['Hot Drinks', 'Moroccan Tea', 25, 'dep-beverage', 31],
    ['Hot Drinks', 'Turkish Coffee', 15, 'dep-beverage', 31],
    ['Hot Drinks', 'Turkish Coffee - 2 Shots', 19, 'dep-beverage', 31],
    ['Hot Drinks', 'French Coffee', 17, 'dep-beverage', 31],
    ['Hot Drinks', 'Nescafe Black', 12, 'dep-beverage', 31],
    ['Hot Drinks', 'Nescafe with Milk', 16, 'dep-beverage', 31],
    ['Hot Drinks', 'Espresso', 13, 'dep-beverage', 31],
    ['Hot Drinks', 'Espresso Double', 17, 'dep-beverage', 31],
    ['Hot Drinks', 'Cappuccino', 17, 'dep-beverage', 31],
    ['Hot Drinks', 'Latte', 17, 'dep-beverage', 31],
    ['Hot Drinks', 'Americano', 15, 'dep-beverage', 31],
    ['Cold Drinks', 'Pepsi', 8, 'dep-beverage', 31],
    ['Cold Drinks', 'Pepsi Diet', 8, 'dep-beverage', 31],
    ['Cold Drinks', '7 Up', 8, 'dep-beverage', 31],
    ['Cold Drinks', '7 Up Diet', 8, 'dep-beverage', 31],
    ['Cold Drinks', 'Mirinda', 8, 'dep-beverage', 31],
    ['Cold Drinks', 'Mountain Dew', 8, 'dep-beverage', 31],
    ['Cold Drinks', 'Sparkling Water', 18, 'dep-beverage', 31],
    ['Cold Drinks', 'Mineral Water [Small]', 4, 'dep-beverage', 31],
    ['Cold Drinks', 'Mineral Water [Large]', 9, 'dep-beverage', 31],
    ['Cold Drinks', 'Voss Water', 18, 'dep-beverage', 31],
    ['Fresh Juices', 'Mango Juice', 27, 'dep-beverage', 32],
    ['Fresh Juices', 'Orange Juice', 20, 'dep-beverage', 32],
    ['Fresh Juices', 'Lemon Juice', 20, 'dep-beverage', 32],
    ['Fresh Juices', 'Strawberry Juice', 27, 'dep-beverage', 32],
    ['Fresh Juices', 'Watermelon Juice', 25, 'dep-beverage', 32],
    ['Fresh Juices', 'Avocado Juice', 29, 'dep-beverage', 32],
    ['Cocktails', 'Mojito Classic', 22, 'dep-beverage', 33],
    ['Cocktails', 'AS Cocktail', 30, 'dep-beverage', 33],
    ['Cocktails', 'Lemon Mint', 25, 'dep-beverage', 33],
    ['Cocktails', 'Maxima', 27, 'dep-beverage', 33],
    ['Fresh Fruits', 'Fruit Salad Special', 35, 'dep-beverage', 34],
    ['Fresh Fruits', 'Watermelon [1 person]', 35, 'dep-kitchen', 34],
    ['Fresh Fruits', 'Fruit Platter [1 person]', 50, 'dep-kitchen', 34],
    ['Dessert', 'Om Ali with Cream & Nuts', 25, 'dep-bakery', 34],
  ];

  const slug = value => String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  window.ImportedMenuMealsBatch = 'AS_MENU_2025-reviewed-v2-shish-tawouk';
  const meals = rows.map(([menuSection, name, sellingPrice, departmentId, menuPage], index) => ({
    id: `meal-menu-2025-${slug(menuSection)}-${slug(name)}`,
    name,
    code: `MENU-${String(index + 1).padStart(3, '0')}`,
    departmentId,
    branch: 'All Branches',
    annualQty: 0,
    sellingPrice,
    ingredients: [],
    employeeIds: [],
    expenseIds: [],
    menuSection,
    menuPage,
    source: 'AS_MENU_2025.pdf',
    costingStatus: 'recipe_pending',
  }));

  const shishTawouk = meals.find(meal => meal.name === 'Shish Tawouk [Plate]');
  Object.assign(shishTawouk, {
    annualQty: 86500,
    ingredients: [
      { materialId: 'mat-chicken', qty: 280, unit: 'g', wastePct: 3 },
      { materialId: 'mat-spice', qty: 14, unit: 'g', wastePct: 0 },
      { materialId: 'mat-bread', qty: 1, unit: 'Piece', wastePct: 0 },
      { materialId: 'mat-hummus', qty: 1, unit: 'Portion', wastePct: 0 },
      { materialId: 'mat-box', qty: 1, unit: 'Piece', wastePct: 0 },
    ],
    employeeIds: ['emp-grill-chef', 'emp-grill-helper'],
    expenseIds: ['exp-rent', 'exp-gas', 'exp-utilities'],
    costingStatus: 'costed',
  });

  window.ImportedMenuMeals = meals;
})();
